### ISSUE TITLE
Consider using `cli/gh-extension-precompile` action to build for primarily supported OS and CPU architectures

### ISSUE THREAD

**Issue by andyfeller** [gclhub/gh-check-github-ip-ranges#2]
### Overview

[`cli/gh-extension-precompile` GitHub Action](https://github.com/cli/gh-extension-precompile) is a convenience that the GitHub CLI team provides to help extension authors build and release for various distributions.  Normally, the workflows created via `gh extension create` will create a workflow that includes this:

Source: [`cli/cli`](https://github.com/cli/cli/blob/trunk/pkg/cmd/extension/ext_tmpls/goBinWorkflow.yml):

```yaml
name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cli/gh-extension-precompile@v2
        with:
          generate_attestations: true
          go_version_file: go.mod
```

As you can see below, this includes new OS and CPU distributions than are currently released:

Source: [`cli/go-gh`](https://github.com/cli/gh-extension-precompile/blob/561b19deda1228a0edf856c3325df87416f8c9bd/build_and_release.sh#L4-L22)

```shell
platforms=(
  darwin-amd64
  darwin-arm64
  freebsd-386
  freebsd-amd64
  freebsd-arm64
  linux-386
  linux-amd64
  linux-arm
  linux-arm64
  windows-386
  windows-amd64
  windows-arm64
)

if [[ "$RELEASE_ANDROID" == "true" ]]; then
  platforms+=("android-amd64")
  platforms+=("android-arm64")
fi
```

The result being a larger population of users you can support.  For example, [`github/gh-copilot` release assets](https://github.com/github/gh-copilot/releases/tag/v1.1.0).
